### ISSUE TITLE
Why we need to handle a subscription property?

### ISSUE THREAD

**Issue by alfredcc** [Zepo/Reflow#2]
```Objective-c
[self.todoStore subscribe:^(RFAction *action) {
        if (action.selector == @selector(actionSetVisibilityFilter:)) {
            self.filterButton.title = [self stringFromVisibilityFilter:[self.todoStore visibilityFilter]];
        }
        self.todos = [self.todoStore visibleTodos];
        [self.tableView reloadData];
    }];
```
I'm very confused about without the `subscription` property, why the block can not called.

**Comment by Zepo** [comment]
Reflow forces developers to retain `subscription`s, otherwise we don't have a chance to `unsubscribe` later which may cause many problems like memory leaks, calling a block with an already deallocated subscriber, etc.
Notice that when all strong references to a `subscription` are gone, the `subscription` will call `unsubscribe` automatically.

**Comment by alfredcc** [comment]
happy new year @Zepo , 
> Note that we should retain the returned `subscription` when calling `subscribe:`. Reflow will not retain it internally and when all strong references to the `subscription` are gone, the `subscription` will call `unsubscribe` automatically.

I'm very sorry because of my carelessness, I did not see it before.
Finally, I look deep into  the code,  but i can't find any code about how automatically `unsubscribe` when none strong reference to the `subscription`. Did I miss something? I'm not a ‘‘old driver’’ on `Objective-C`.
